services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServerPw!"
      ACCEPT_EULA: "Y"
    ports:
      - "1432:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./db/01-Migracao.sql:/tmp/01-Migracao.sql
      - ./db/init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh