version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server2019
    environment:
      SA_PASSWORD: "SqlServerPw!"
      ACCEPT_EULA: "Y"
    ports:
      - "1432:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./db/01-Migracao.sql:/tmp/01-Migracao.sql
      - ./db/init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh

  agenda.webapp:
    image: ${DOCKER_REGISTRY-}agendawebapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    depends_on:
      - sqlserver

